baseurl = "http://www.satanb4.github.io/"
title = "Home"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "monokai"

[params]
  author = "Sayan B"
  info = ["PhD Student - Quantum Physics", "Fullstack Systems Engineer"]
  description = "Sayan B's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/main.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["layouts/css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["layouts/js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/satanb4"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/sayan-bandyopadhyay/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "blog/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Portfolio"
  weight = 3
  url = "portfolio/"
